### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by zone117x** [blinkhash/foundation-v2-server#17]
Saw the following error:
```
tbtc-mining-foundation-1  | [3/9/2023, 6:12:43 PM] [LOG] (Pool-Bitcoin) foundation:shares - A share was accepted at difficulty 524288/646909.43873721 by tb1qu7j4z6826sh48fc8kpfcdv5hdtuyz4qu2cncel [::ffff:104.131.104.33]
tbtc-mining-postgres-1    | 2023-03-09 18:12:44.787 UTC [2851] ERROR:  column "undefined" does not exist at character 679
tbtc-mining-postgres-1    | 2023-03-09 18:12:44.787 UTC [2851] STATEMENT:  BEGIN; 
tbtc-mining-postgres-1    | 	      INSERT INTO "Pool-Bitcoin".local_shares (
tbtc-mining-postgres-1    | 	        error, uuid, timestamp,
tbtc-mining-postgres-1    | 	        submitted, ip, port, addrprimary,
tbtc-mining-postgres-1    | 	        addrauxiliary, blockdiffprimary,
tbtc-mining-postgres-1    | 	        blockdiffauxiliary, blockvalid,
tbtc-mining-postgres-1    | 	        blocktype, clientdiff, hash, height,
tbtc-mining-postgres-1    | 	        identifier, reward, sharediff,
tbtc-mining-postgres-1    | 	        sharevalid, transaction)
tbtc-mining-postgres-1    | 	      VALUES (
tbtc-mining-postgres-1    | 	        'job not found',
tbtc-mining-postgres-1    | 	        '75f2d853-918f-4a66-9c01-9a5b02a46343',
tbtc-mining-postgres-1    | 	        1678385564786,
tbtc-mining-postgres-1    | 	        1678385564786,
tbtc-mining-postgres-1    | 	        '::ffff:104.131.104.33',
tbtc-mining-postgres-1    | 	        '3002',
tbtc-mining-postgres-1    | 	        'tb1qu7j4z6826sh48fc8kpfcdv5hdtuyz4qu2cncel',
tbtc-mining-postgres-1    | 	        '',
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        'share',
tbtc-mining-postgres-1    | 	        524288,
tbtc-mining-postgres-1    | 	        'undefined',
tbtc-mining-postgres-1    | 	        undefined,
tbtc-mining-postgres-1    | 	        '',
tbtc-mining-postgres-1    | 	        undefined,
tbtc-mining-postgres-1    | 	        undefined,
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        '')
tbtc-mining-postgres-1    | 	      ON CONFLICT ON CONSTRAINT local_shares_unique
tbtc-mining-postgres-1    | 	      DO NOTHING; COMMIT;
tbtc-mining-foundation-1  | [3/9/2023, 6:12:44 PM] [ERROR] (Worker) foundation:database - An error was thrown when trying to execute a query (BEGIN; 
tbtc-mining-foundation-1  |       INSERT INTO "Pool-Bitcoin".local_shares (
tbtc-mining-foundation-1  |         error, uuid, timestamp,
tbtc-mining-foundation-1  |         submitted, ip, port, addrprimary,
tbtc-mining-foundation-1  |         addrauxiliary, blockdiffprimary,
tbtc-mining-foundation-1  |         blockdiffauxiliary, blockvalid,
tbtc-mining-foundation-1  |         blocktype, clientdiff, hash, height,
tbtc-mining-foundation-1  |         identifier, reward, sharediff,
tbtc-mining-foundation-1  |         sharevalid, transaction)
tbtc-mining-foundation-1  |       VALUES (
tbtc-mining-foundation-1  |         'job not found',
tbtc-mining-foundation-1  |         '75f2d853-918f-4a66-9c01-9a5b02a46343',
tbtc-mining-foundation-1  |         1678385564786,
tbtc-mining-foundation-1  |         1678385564786,
tbtc-mining-foundation-1  |         '::ffff:104.131.104.33',
tbtc-mining-foundation-1  |         '3002',
tbtc-mining-foundation-1  |         'tb1qu7j4z6826sh48fc8kpfcdv5hdtuyz4qu2cncel',
tbtc-mining-foundation-1  |         '',
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         'share',
tbtc-mining-foundation-1  |         524288,
tbtc-mining-foundation-1  |         'undefined',
tbtc-mining-foundation-1  |         undefined,
tbtc-mining-foundation-1  |         '',
tbtc-mining-foundation-1  |         undefined,
tbtc-mining-foundation-1  |         undefined,
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         '')
tbtc-mining-foundation-1  |       ON CONFLICT ON CONSTRAINT local_shares_unique
tbtc-mining-foundation-1  |       DO NOTHING; COMMIT;): {"length":110,"name":"error","severity":"ERROR","code":"42703","position":"679","file":"parse_relation.c","line":"3633","routine":"errorMissingColumn"}
tbtc-mining-foundation-1  | /app/database/main/worker/commands.js:26
tbtc-mining-foundation-1  |     const handler = (error) => { throw new Error(error); };
tbtc-mining-foundation-1  |                                  ^
tbtc-mining-foundation-1  | 
tbtc-mining-foundation-1  | Error: error: column "undefined" does not exist
tbtc-mining-foundation-1  |     at handler (/app/database/main/worker/commands.js:26:40)
tbtc-mining-foundation-1  |     at Query.callback (/app/database/main/worker/commands.js:31:9)
tbtc-mining-foundation-1  |     at Query.handleError (/app/node_modules/pg/lib/query.js:128:19)
tbtc-mining-foundation-1  |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:335:17)
tbtc-mining-foundation-1  |     at Connection.emit (events.js:400:28)
tbtc-mining-foundation-1  |     at /app/node_modules/pg/lib/connection.js:114:12
tbtc-mining-foundation-1  |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
tbtc-mining-foundation-1  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
tbtc-mining-foundation-1  |     at Socket.emit (events.js:400:28)
tbtc-mining-foundation-1  |     at addChunk (internal/streams/readable.js:293:12)
tbtc-mining-foundation-1  | [3/9/2023, 6:12:44 PM] [ERROR] (Workers) foundation:builder - Fork 0 died, starting replacement worker ...
```

Config is all pretty basic -- essentially using the example config. My whole setup can be found here: https://github.com/zone117x/tbtc-mining/tree/v2

**Comment by zone117x** [comment]
Another:
```
tbtc-mining-postgres-1    | 2023-03-09 19:53:43.927 UTC [105448] ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
tbtc-mining-postgres-1    | 2023-03-09 19:53:43.927 UTC [105448] HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
tbtc-mining-postgres-1    | 2023-03-09 19:53:43.927 UTC [105448] STATEMENT:  BEGIN; 
tbtc-mining-postgres-1    | 	      DELETE FROM "Pool-Bitcoin".current_blocks
tbtc-mining-postgres-1    | 	      WHERE round IN ('7d5d0ac3-7d82-4059-b823-3af9444797d4', '1152a947-c8a7-4340-9055-72d6282bb8d3', '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c', '1d337b9f-5553-4c28-9ca3-31b248d78746'); 
tbtc-mining-postgres-1    | 	      DELETE FROM "Pool-Bitcoin".current_rounds
tbtc-mining-postgres-1    | 	      WHERE round IN ('7d5d0ac3-7d82-4059-b823-3af9444797d4', '1152a947-c8a7-4340-9055-72d6282bb8d3', '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c', '1d337b9f-5553-4c28-9ca3-31b248d78746'); 
tbtc-mining-postgres-1    | 	      INSERT INTO "Pool-Bitcoin".current_rounds (
tbtc-mining-postgres-1    | 	        timestamp, submitted, recent,
tbtc-mining-postgres-1    | 	        miner, worker, identifier, invalid,
tbtc-mining-postgres-1    | 	        round, solo, stale, times, type,
tbtc-mining-postgres-1    | 	        valid, work)
tbtc-mining-postgres-1    | 	      VALUES (
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391400000,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        'current',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        5517.442,
tbtc-mining-postgres-1    | 	        'primary',
tbtc-mining-postgres-1    | 	        4141,
tbtc-mining-postgres-1    | 	        2410247451.5414658), (
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391400000,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        'current',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        1.498,
tbtc-mining-postgres-1    | 	        'primary',
tbtc-mining-postgres-1    | 	        4,
tbtc-mining-postgres-1    | 	        4411590.53913134), (
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391400000,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        'current',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        414.345,
tbtc-mining-postgres-1    | 	        'primary',
tbtc-mining-postgres-1    | 	        277,
tbtc-mining-postgres-1    | 	        345265218.2215358), (
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678391400000,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        'current',
tbtc-mining-foundation-1  | [3/9/2023, 7:53:43 PM] [ERROR] (Master) foundation:database - An error was thrown when trying to execute a query (BEGIN; 
tbtc-mining-foundation-1  |       DELETE FROM "Pool-Bitcoin".current_blocks
tbtc-mining-foundation-1  |       WHERE round IN ('7d5d0ac3-7d82-4059-b823-3af9444797d4', '1152a947-c8a7-4340-9055-72d6282bb8d3', '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c', '1d337b9f-5553-4c28-9ca3-31b248d78746'); 
tbtc-mining-foundation-1  |       DELETE FROM "Pool-Bitcoin".current_rounds
tbtc-mining-foundation-1  |       WHERE round IN ('7d5d0ac3-7d82-4059-b823-3af9444797d4', '1152a947-c8a7-4340-9055-72d6282bb8d3', '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c', '1d337b9f-5553-4c28-9ca3-31b248d78746'); 
tbtc-mining-foundation-1  |       INSERT INTO "Pool-Bitcoin".current_rounds (
tbtc-mining-foundation-1  |         timestamp, submitted, recent,
tbtc-mining-foundation-1  |         miner, worker, identifier, invalid,
tbtc-mining-foundation-1  |         round, solo, stale, times, type,
tbtc-mining-foundation-1  |         valid, work)
tbtc-mining-foundation-1  |       VALUES (
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391400000,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         'current',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         5517.442,
tbtc-mining-foundation-1  |         'primary',
tbtc-mining-foundation-1  |         4141,
tbtc-mining-foundation-1  |         2410247451.5414658), (
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391400000,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         'current',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         1.498,
tbtc-mining-foundation-1  |         'primary',
tbtc-mining-foundation-1  |         4,
tbtc-mining-foundation-1  |         4411590.53913134), (
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391400000,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         'current',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         414.345,
tbtc-mining-foundation-1  |         'primary',
tbtc-mining-foundation-1  |         277,
tbtc-mining-foundation-1  |         345265218.2215358), (
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678391400000,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         'current',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         'primary',
tbtc-mining-foundation-1  |         1,
tbtc-mining-foundation-1  |         13222428.13186811)
tbtc-mining-foundation-1  |       ON CONFLICT ON CONSTRAINT current_rounds_unique
tbtc-mining-foundation-1  |       DO UPDATE SET
tbtc-mining-foundation-1  |         timestamp = EXCLUDED.timestamp,
tbtc-mining-foundation-1  |         submitted = EXCLUDED.submitted,
tbtc-mining-foundation-1  |         invalid = "Pool-Bitcoin".current_rounds.invalid + EXCLUDED.invalid,
tbtc-mining-foundation-1  |         stale = "Pool-Bitcoin".current_rounds.stale + EXCLUDED.stale,
tbtc-mining-foundation-1  |         times = GREATEST("Pool-Bitcoin".current_rounds.times, EXCLUDED.times),
tbtc-mining-foundation-1  |         valid = "Pool-Bitcoin".current_rounds.valid + EXCLUDED.valid,
tbtc-mining-foundation-1  |         work = "Pool-Bitcoin".current_rounds.work + EXCLUDED.work; 
tbtc-mining-foundation-1  |       INSERT INTO "Pool-Bitcoin".historical_blocks (
tbtc-mining-foundation-1  |         timestamp, submitted, miner,
tbtc-mining-foundation-1  |         worker, category, confirmations,
tbtc-mining-foundation-1  |         difficulty, hash, height,
tbtc-mining-foundation-1  |         identifier, luck, reward,
tbtc-mining-foundation-1  |         round, solo, transaction,
tbtc-mining-foundation-1  |         type)
tbtc-mining-foundation-1  |       VALUES (
tbtc-mining-foundation-1  |         1678391623925,
tbtc-mining-foundation-1  |         1678390115538,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'orphan',
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         102149233.88926451,
tbtc-mining-foundation-1  |         '0000000000000027407d250afa2890d47dda3e8c569e7a41f2061481517734b7',
tbtc-mining-foundation-1  |         2423588,
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         13.67,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         '7d5d0ac3-7d82-4059-b823-3af9444797d4',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         '09ef976670c469c3f6a5e5743523d25f98d2e51e729b76aa4c697fc9c60ce1a1',
tbtc-mining-foundation-1  |         'primary'), (
tbtc-mining-foundation-1  |         1678391623926,
tbtc-mining-foundation-1  |         1678390151175,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'orphan',
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         102149233.88926451,
tbtc-mining-foundation-1  |         '000000000000001b6eb16387e8d827d5c71be31a075d84f98bd02d46d592845c',
tbtc-mining-foundation-1  |         2423589,
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         4.32,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         '1152a947-c8a7-4340-9055-72d6282bb8d3',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         '5cb61e03e7d95272bc94fcec9cad53ea5bfcb0004e1b1bdde2c30b84d5af3595',
tbtc-mining-foundation-1  |         'primary'), (
tbtc-mining-foundation-1  |         1678391623926,
tbtc-mining-foundation-1  |         1678391203335,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'orphan',
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         102149233.88926451,
tbtc-mining-foundation-1  |         '00000000000000015ab5444b493681c53fe4b6b801a4cd83bac525c5e32ca5bb',
tbtc-mining-foundation-1  |         2423597,
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         3.59,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         '1f3ff455e43519a441a9069c00e4bd85ffbdde960372b3138f182e03c5e6a837',
tbtc-mining-foundation-1  |         'primary'), (
tbtc-mining-foundation-1  |         1678391623926,
tbtc-mining-foundation-1  |         1678391203343,
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-foundation-1  |         'orphan',
tbtc-mining-foundation-1  |         -1,
tbtc-mining-foundation-1  |         102149233.88926451,
tbtc-mining-foundation-1  |         '000000000000001456e7526abd8f700bb2396e8da4fa9482c8d6b31f8b77cef8',
tbtc-mining-foundation-1  |         2423598,
tbtc-mining-foundation-1  |         'master',
tbtc-mining-foundation-1  |         12.94,
tbtc-mining-foundation-1  |         0,
tbtc-mining-foundation-1  |         '1d337b9f-5553-4c28-9ca3-31b248d78746',
tbtc-mining-foundation-1  |         false,
tbtc-mining-foundation-1  |         'c88f6432d10ae9228340f56365f9bb9b4f94bf6fa4af1525b9f6344da3cabd0e',
tbtc-mining-foundation-1  |         'primary')
tbtc-mining-foundation-1  |       ON CONFLICT DO NOTHING; COMMIT;): {"length":239,"name":"error","severity":"ERROR","code":"21000","hint":"Ensure that no rows proposed for insertion within the same command have duplicate constrained values.","file":"nodeModifyTable.c","line":"2176","routine":"ExecOnConflictUpdate"}
tbtc-mining-foundation-1  | /app/database/main/master/commands.js:44
tbtc-mining-foundation-1  |     const handler = (error) => { throw new Error(error); };
tbtc-mining-foundation-1  |                                  ^
tbtc-mining-foundation-1  | 
tbtc-mining-foundation-1  | Error: error: ON CONFLICT DO UPDATE command cannot affect row a second time
tbtc-mining-foundation-1  |     at handler (/app/database/main/master/commands.js:44:40)
tbtc-mining-foundation-1  |     at Query.callback (/app/database/main/master/commands.js:49:9)
tbtc-mining-foundation-1  |     at Query.handleError (/app/node_modules/pg/lib/query.js:128:19)
tbtc-mining-foundation-1  |     at Client._handleErrorMessage (/app/node_modules/pg/lib/client.js:335:17)
tbtc-mining-foundation-1  |     at Connection.emit (events.js:400:28)
tbtc-mining-foundation-1  |     at /app/node_modules/pg/lib/connection.js:114:12
tbtc-mining-foundation-1  |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:40:17)
tbtc-mining-foundation-1  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
tbtc-mining-foundation-1  |     at Socket.emit (events.js:400:28)
tbtc-mining-foundation-1  |     at addChunk (internal/streams/readable.js:293:12)
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        'primary',
tbtc-mining-postgres-1    | 	        1,
tbtc-mining-postgres-1    | 	        13222428.13186811)
tbtc-mining-postgres-1    | 	      ON CONFLICT ON CONSTRAINT current_rounds_unique
tbtc-mining-postgres-1    | 	      DO UPDATE SET
tbtc-mining-postgres-1    | 	        timestamp = EXCLUDED.timestamp,
tbtc-mining-postgres-1    | 	        submitted = EXCLUDED.submitted,
tbtc-mining-postgres-1    | 	        invalid = "Pool-Bitcoin".current_rounds.invalid + EXCLUDED.invalid,
tbtc-mining-postgres-1    | 	        stale = "Pool-Bitcoin".current_rounds.stale + EXCLUDED.stale,
tbtc-mining-postgres-1    | 	        times = GREATEST("Pool-Bitcoin".current_rounds.times, EXCLUDED.times),
tbtc-mining-postgres-1    | 	        valid = "Pool-Bitcoin".current_rounds.valid + EXCLUDED.valid,
tbtc-mining-postgres-1    | 	        work = "Pool-Bitcoin".current_rounds.work + EXCLUDED.work; 
tbtc-mining-postgres-1    | 	      INSERT INTO "Pool-Bitcoin".historical_blocks (
tbtc-mining-postgres-1    | 	        timestamp, submitted, miner,
tbtc-mining-postgres-1    | 	        worker, category, confirmations,
tbtc-mining-postgres-1    | 	        difficulty, hash, height,
tbtc-mining-postgres-1    | 	        identifier, luck, reward,
tbtc-mining-postgres-1    | 	        round, solo, transaction,
tbtc-mining-postgres-1    | 	        type)
tbtc-mining-postgres-1    | 	      VALUES (
tbtc-mining-postgres-1    | 	        1678391623925,
tbtc-mining-postgres-1    | 	        1678390115538,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'orphan',
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        102149233.88926451,
tbtc-mining-postgres-1    | 	        '0000000000000027407d250afa2890d47dda3e8c569e7a41f2061481517734b7',
tbtc-mining-postgres-1    | 	        2423588,
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        13.67,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        '7d5d0ac3-7d82-4059-b823-3af9444797d4',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        '09ef976670c469c3f6a5e5743523d25f98d2e51e729b76aa4c697fc9c60ce1a1',
tbtc-mining-postgres-1    | 	        'primary'), (
tbtc-mining-postgres-1    | 	        1678391623926,
tbtc-mining-postgres-1    | 	        1678390151175,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'orphan',
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        102149233.88926451,
tbtc-mining-postgres-1    | 	        '000000000000001b6eb16387e8d827d5c71be31a075d84f98bd02d46d592845c',
tbtc-mining-postgres-1    | 	        2423589,
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        4.32,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        '1152a947-c8a7-4340-9055-72d6282bb8d3',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        '5cb61e03e7d95272bc94fcec9cad53ea5bfcb0004e1b1bdde2c30b84d5af3595',
tbtc-mining-postgres-1    | 	        'primary'), (
tbtc-mining-postgres-1    | 	        1678391623926,
tbtc-mining-postgres-1    | 	        1678391203335,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'orphan',
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        102149233.88926451,
tbtc-mining-postgres-1    | 	        '00000000000000015ab5444b493681c53fe4b6b801a4cd83bac525c5e32ca5bb',
tbtc-mining-postgres-1    | 	        2423597,
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        3.59,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        '3f33caee-0fe1-4bd9-8d8f-eecb58633d1c',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        '1f3ff455e43519a441a9069c00e4bd85ffbdde960372b3138f182e03c5e6a837',
tbtc-mining-postgres-1    | 	        'primary'), (
tbtc-mining-postgres-1    | 	        1678391623926,
tbtc-mining-postgres-1    | 	        1678391203343,
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'tb1qc7sfev9vr5w5uqsft7rmy23s42yx50rac8ftrw',
tbtc-mining-postgres-1    | 	        'orphan',
tbtc-mining-postgres-1    | 	        -1,
tbtc-mining-postgres-1    | 	        102149233.88926451,
tbtc-mining-postgres-1    | 	        '000000000000001456e7526abd8f700bb2396e8da4fa9482c8d6b31f8b77cef8',
tbtc-mining-postgres-1    | 	        2423598,
tbtc-mining-postgres-1    | 	        'master',
tbtc-mining-postgres-1    | 	        12.94,
tbtc-mining-postgres-1    | 	        0,
tbtc-mining-postgres-1    | 	        '1d337b9f-5553-4c28-9ca3-31b248d78746',
tbtc-mining-postgres-1    | 	        false,
tbtc-mining-postgres-1    | 	        'c88f6432d10ae9228340f56365f9bb9b4f94bf6fa4af1525b9f6344da3cabd0e',
tbtc-mining-postgres-1    | 	        'primary')
tbtc-mining-postgres-1    | 	      ON CONFLICT DO NOTHING; COMMIT;
tbtc-mining-postgres-1    | 2023-03-09 19:53:43.957 UTC [105448] LOG:  could not receive data from client: Connection reset by peer
tbtc-mining-foundation-1  | [3/9/2023, 7:53:43 PM] [ERROR] (Workers) foundation:builder - Fork 1 died, starting replacement worker ...

```

**Comment by blinkhash** [comment]
Fixed in https://github.com/blinkhash/foundation-v2-server/commit/956a380f89f8b2bf545736b4b1dfb7c171b88755, thanks!
