### ISSUE TITLE
An error was thrown when trying to execute a query

### ISSUE THREAD

**Issue by mymuzk** [blinkhash/foundation-v2-server#6]
The following error will be displayed when the miner links to the pool：
(Commands) foundation:database - An error was thrown when trying to execute a query: {"length":105,"name":"error","severity":"ERROR","code":"42703","position":"2195","file":"parse_relation.c","line":"3643","routine":"errorMissingColumn"}
/home/pool/foundation-server/database/main/commands.js:43
    const handler = (error) => { throw new Error(error); };
                                 ^

Error: error: column "nan" does not exist
    at handler (/home/pool/foundation-server/database/main/commands.js:43:40)
    at Query.callback (/home/pool/foundation-server/database/main/commands.js:48:9)
    at Query.handleError (/home/pool/foundation-server/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/home/pool/foundation-server/node_modules/pg/lib/client.js:335:17)
    at Connection.emit (events.js:311:20)
    at /home/pool/foundation-server/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/home/pool/foundation-server/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/pool/foundation-server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
[10/14/2022, 2:13:28 PM] [ERROR] (Workers) foundation:builder - Fork 1 died, starting replacement worker ...
[10/14/2022, 2:13:29 PM] [LOG] (Pool-Litecoin-Dogecoin) foundation:pool - Authorized worker: tltc1qlmjdcu0w05qdufpfy3n0qefds4janfd3zu5hng.ltc (::ffff:127.0.0.1:3002)
[10/14/2022, 2:13:30 PM] [ERROR] (Commands) foundation:database - An error was thrown when trying to execute a query: {"length":105,"name":"error","severity":"ERROR","code":"42703","position":"2195","file":"parse_relation.c","line":"3643","routine":"errorMissingColumn"}
/home/pool/foundation-server/database/main/commands.js:43
    const handler = (error) => { throw new Error(error); };
                                 ^

Error: error: column "nan" does not exist
    at handler (/home/pool/foundation-server/database/main/commands.js:43:40)
    at Query.callback (/home/pool/foundation-server/database/main/commands.js:48:9)
    at Query.handleError (/home/pool/foundation-server/node_modules/pg/lib/query.js:128:19)
    at Client._handleErrorMessage (/home/pool/foundation-server/node_modules/pg/lib/client.js:335:17)
    at Connection.emit (events.js:311:20)
    at /home/pool/foundation-server/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/home/pool/foundation-server/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/pool/foundation-server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
[10/14/2022, 2:13:30 PM] [ERROR] (Workers) foundation:builder - Fork 0 died, starting replacement worker ...

**Comment by drmancini** [comment]
This looks like you have used a newer version of foundation on an older database structure as you are trying to access a column that doesn't exist. Delete the database and restart foundation server.

**Comment by mymuzk** [comment]
Thank you It works
